server:
  port : 8090

# the logging configuration is here
logging:
  level:
    root: INFO
    com.akg: DEBUG

common:
  type: webFlux # async, mvc, webFlux
  number-of-executions: 50000
  fake-http-server-url: http://localhost:9090/imitateWork?timeInMs=
  time-in-ms: 150
  thread-queue-capacity: 50000
  thread-max-pool-size: 100
  thread-core-pool-size: 100